name: Generate Documentation
on:
  workflow_dispatch:
    description: 'Manual run'
  push:
    branches-ignore:
      - 'dependabot/**'

jobs:
  runService:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Start NatsMQ
        uses: onichandame/nats-action@master
        with:
          port: "4222"
      - name: Build
        run: |
          pushd interfaces
          npm install
          npm run build
          popd
          pushd common
          npm install
          npm run build
          popd
            pushd api-gateway
            npm install
            npm run build
            popd
        env:
          CI: true
      - name: Run service
        run: |
          pushd api-gateway
          npm start &
          popd
      - name: Download file
        run: |
          sleep 30
          pwd
          ls
