name: Sync Upstream Develop

env:
  BRANCH: develop
  
# This runs every day on 1801 UTC
on:
  schedule:
    - cron: '1 */6 * * *'
  # Allows manual workflow run (must in default branch to work)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout target repo
      uses: actions/checkout@v3.3.0
      with:
        ref:  ${{ env.BRANCH }}
        fetch-depth: '0'
        token: ${{ secrets.WORKFLOW_TOKEN }}
    
    - name: Upstream Sync
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
      with:
        target_sync_branch: ${{ env.BRANCH }}
        target_repo_token: ${{ secrets.WORKFLOW_TOKEN }}
        upstream_repo_access_token: ${{ secrets.WORKFLOW_TOKEN }}
        upstream_sync_repo: ${{ vars.UPSTREAM_REPOSITORY }}
        upstream_sync_branch: ${{ env.BRANCH }}
        upstream_pull_args: --unshallow
        # target_branch_push_args: --tags
        git_config_pull_rebase: true
        #shallow_since: 2 hours ago

    - run: echo "New commits found"
      if: steps.sync.outputs.has_new_commits == true
