name: Sync Upstream Develop

env:
  LE_BRANCH: develop
  
# This runs every day on 1801 UTC
on:
  schedule:
    - cron: '1 9,15 * * *'
  # Allows manual workflow run (must in default branch to work)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout target repo
      uses: actions/checkout@v3.3.0
      with:
        ref:  ${{ env.BRANCH }}
    
    - name: Upstream Sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
      with:
        target_sync_branch: ${{ env.BRANCH }}
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_repo: ${{ vars.UPSTREAM_REPOSITORY }}
        upstream_sync_branch: ${{ env.BRANCH }}
